'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class EventRecorderEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=EventRecorderEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property C__EFMigrationsHistory() As DbSet(Of C__EFMigrationsHistory)
    Public Overridable Property ActionTargets() As DbSet(Of ActionTarget)
    Public Overridable Property Events() As DbSet(Of [Event])
    Public Overridable Property EventSources() As DbSet(Of EventSource)

    Public Overridable Function AddEvent(iDActionTarget As Nullable(Of System.Guid), iDEventSource As Nullable(Of System.Guid), description As String, bookingDate As Nullable(Of System.DateTimeOffset), startTime As Nullable(Of System.TimeSpan), endTime As Nullable(Of System.TimeSpan), durationTicks As Nullable(Of Long), newId As Nullable(Of System.Guid)) As Integer
        Dim iDActionTargetParameter As ObjectParameter = If(iDActionTarget.HasValue, New ObjectParameter("IDActionTarget", iDActionTarget), New ObjectParameter("IDActionTarget", GetType(System.Guid)))

        Dim iDEventSourceParameter As ObjectParameter = If(iDEventSource.HasValue, New ObjectParameter("IDEventSource", iDEventSource), New ObjectParameter("IDEventSource", GetType(System.Guid)))

        Dim descriptionParameter As ObjectParameter = If(description IsNot Nothing, New ObjectParameter("Description", description), New ObjectParameter("Description", GetType(String)))

        Dim bookingDateParameter As ObjectParameter = If(bookingDate.HasValue, New ObjectParameter("BookingDate", bookingDate), New ObjectParameter("BookingDate", GetType(System.DateTimeOffset)))

        Dim startTimeParameter As ObjectParameter = If(startTime.HasValue, New ObjectParameter("StartTime", startTime), New ObjectParameter("StartTime", GetType(System.TimeSpan)))

        Dim endTimeParameter As ObjectParameter = If(endTime.HasValue, New ObjectParameter("EndTime", endTime), New ObjectParameter("EndTime", GetType(System.TimeSpan)))

        Dim durationTicksParameter As ObjectParameter = If(durationTicks.HasValue, New ObjectParameter("DurationTicks", durationTicks), New ObjectParameter("DurationTicks", GetType(Long)))

        Dim newIdParameter As ObjectParameter = If(newId.HasValue, New ObjectParameter("NewId", newId), New ObjectParameter("NewId", GetType(System.Guid)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("AddEvent", iDActionTargetParameter, iDEventSourceParameter, descriptionParameter, bookingDateParameter, startTimeParameter, endTimeParameter, durationTicksParameter, newIdParameter)
    End Function

End Class
