'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EventSource
    Public Property IdEventSource As System.Guid
    Public Property DateCreated As System.DateTimeOffset
    Public Property DateLastEdited As System.DateTimeOffset
    Public Property Name As String
    Public Property Description As String

    Public Overridable Property Events As ICollection(Of [Event]) = New HashSet(Of [Event])

End Class
