'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class [Event]
    Public Property IdEvent As System.Guid
    Public Property ActionTargetIdActionTarget As Nullable(Of System.Guid)
    Public Property DateCreated As System.DateTimeOffset
    Public Property DateLastEdited As System.DateTimeOffset
    Public Property Description As String
    Public Property Duration As Nullable(Of Long)
    Public Property EndTime As Nullable(Of System.TimeSpan)
    Public Property EventSourceIdEventSource As Nullable(Of System.Guid)
    Public Property StartTime As Nullable(Of System.TimeSpan)
    Public Property BookingDate As Nullable(Of System.DateTimeOffset)

    Public Overridable Property ActionTarget As ActionTarget
    Public Overridable Property EventSource As EventSource

End Class
